-----BEGIN-----
-----SETTINGS-----
STRATEGY:feddf
MODEL_NAME:resnet8
NUM_CLIENTS:20
NUM_ROUNDS:30
FRACTION_FIT:0.4
FRACTION_EVALUATE:0.0
DATASET_NAME:pathmnist
PARTITION_ALPHA:1.0
PARTITION_VAL_RATIO:0.1
BATCH_SIZE:512
LOCAL_EPOCHS:40
LOCAL_LR:0.05
DISTILL_BATCH_SIZE:512
SERVER_LR:0.005
SERVER_STEPS:500
SERVER_EARLY_STEPS:1000
USE_EARLY_STOPPING:False
USE_ADAPTIVE_LR:False
SEED:42
CUDA_DETERMINISTIC:False
USE_CROPS:True
IMG_NAME:colonpath_sample.jpg
DISTILL_DATASET:cifar100
DISTILL_ALPHA:1.0
NUM_DISTILL_IMAGES:10000
DISTILL_TRANSFORMS:v0
WARM_START:True
WARM_START_ROUNDS:1
WARM_START_INTERVAL:5
KMEANS_N_CLUSTER:20
KMEANS_HEURISTICS:easy
KMEANS_MIXED_FACTOR:50-50
CLIPPING_FACTOR:3
KMEANS_BALANCING:10%
-----SETTINGS END-----
-----EXPERIMENT BEGINS-----
---------
Generating crops for FedDF
Namespace(img_size=32, batch_size=32, num_imgs=100000, threads=18, vflip=False, deg=30, shear=30, cropfirst=True, initcrop=0.5, scale=[500, 1], randinterp=False, debug=False, imgpath='./static/single_images/colonpath_sample.jpg', targetpath='/scratch-local/sunnys.3063431/1689290967_083341884', seed=42, img_per_thread=5555)
will save 100000 patches in /scratch-local/sunnys.3063431/1689290967_083341884/single_img_crops/crops
100000 took 0.47min with 18 threads
---------
Simulating feddf training
INFO simulate 2023-07-14 01:30:15,475 | simulate.py:50 | Python script started : simulate.py
DEBUG simulate 2023-07-14 01:30:15,476 | simulate.py:55 | Reading args from argument parser
Downloading https://zenodo.org/record/6496656/files/pathmnist.npz?download=1 to /scratch-local/sunnys.3063431/1689290967_083341884/pathmnist.npz
Generating unified pathmnist dataset
Class histogram for 0-th partition (alpha=1.0, 9 classes): [ 797  772  834   92   22  456  457 1046   24]
INFO flwr 2023-07-14 01:30:37,260 | app.py:145 | Starting Flower simulation, config: ServerConfig(num_rounds=30, round_timeout=None)
2023-07-14 01:30:40,044	INFO worker.py:1529 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
INFO flwr 2023-07-14 01:30:41,384 | app.py:179 | Flower VCE: Ray initialized with resources: {'CPU': 18.0, 'node:145.136.62.36': 1.0, 'object_store_memory': 61847529062.0, 'memory': 103079215104.0, 'GPU': 1.0, 'accelerator_type:A100': 1.0}
INFO flwr 2023-07-14 01:30:41,384 | server.py:86 | Initializing global parameters
INFO flwr 2023-07-14 01:30:41,384 | server.py:266 | Using initial parameters provided by strategy
INFO flwr 2023-07-14 01:30:41,384 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-07-14 01:30:50,499 | server.py:91 | initial parameters (loss, other metrics): 2.1845225108367154, {'server_test_acc': 0.11030640668523677}
INFO flwr 2023-07-14 01:30:50,499 | server.py:101 | FL starting
DEBUG flwr 2023-07-14 01:30:58,335 | server.py:215 | fit_round 1: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2855070)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2855074)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2855071)[0m double free or corruption (fasttop)
DEBUG flwr 2023-07-14 01:32:17,002 | server.py:229 | fit_round 1 received 8 results and 0 failures
Cluster score for round 1 = 1282.557373046875
[2m[36m(launch_and_fit pid=2855067)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2855069)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2855073)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2855070)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2855071)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2855072)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2855068)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2855074)[0m Fitting Client 12
Warm start at round 1
Performing server side distillation training...
[2m[36m(launch_and_fit pid=2855069)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2855072)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2855073)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2855068)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2855067)[0m double free or corruption (fasttop)
E0714 01:32:19.168565667 2852734 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0714 01:32:19.172257981 2852734 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0714 01:32:19.172278413 2852734 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0714 01:32:19.172287696 2852734 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0714 01:32:19.172295485 2852734 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0714 01:32:19.172303491 2852734 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
E0714 01:32:19.172310023 2852734 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 60000ms
Distillation training stopped at step number : 500
Average fusion training loss : 0.2664649935662746, val accuracy : 0.4510449088483771, best val accuracy : 0.4862160960426856
Average local training loss : 7.0622634055092925
Average local training accuracy : 0.748891975308642
INFO flwr 2023-07-14 01:33:06,788 | server.py:116 | fit progress: (1, 3.2893234667339697, {'server_test_acc': 0.4488857938718663}, 136.28860840492416)
INFO flwr 2023-07-14 01:33:06,788 | server.py:163 | evaluate_round 1: no clients selected, cancel
DEBUG flwr 2023-07-14 01:33:14,591 | server.py:215 | fit_round 2: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2998111)[0m double free or corruption (fasttop)
DEBUG flwr 2023-07-14 01:34:31,202 | server.py:229 | fit_round 2 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2998112)[0m malloc_consolidate(): invalid chunk size
Cluster score for round 2 = 183628.6875
[2m[36m(launch_and_fit pid=2998107)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=2998111)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2998112)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2998109)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2998110)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2998115)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=2998113)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2998114)[0m Fitting Client 15
Performing server side distillation training...
[2m[36m(launch_and_fit pid=2998110)[0m double free or corruption (fasttop)
E0714 01:34:32.250939261 3179194 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 120000ms
[2m[36m(launch_and_fit pid=2998115)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2998109)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2998113)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2998114)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2998107)[0m double free or corruption (fasttop)
Distillation training stopped at step number : 500
Average fusion training loss : 0.25242122849822046, val accuracy : 0.5208203646064918, best val accuracy : 0.5899288572698977
Average local training loss : 5.344014029111713
Average local training accuracy : 0.8375601851851852
INFO flwr 2023-07-14 01:35:30,239 | server.py:116 | fit progress: (2, 2.426374108147156, {'server_test_acc': 0.42938718662952646}, 279.73937643296085)
INFO flwr 2023-07-14 01:35:30,239 | server.py:163 | evaluate_round 2: no clients selected, cancel
DEBUG flwr 2023-07-14 01:35:38,472 | server.py:215 | fit_round 3: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3269932)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3269933)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3269931)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3270002)[0m double free or corruption (!prev)
[2m[36m(launch_and_fit pid=3269934)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-07-14 01:36:57,238 | server.py:229 | fit_round 3 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3269776)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3270003)[0m malloc_consolidate(): invalid chunk size
Cluster score for round 3 = 136845.59375
[2m[36m(launch_and_fit pid=3269932)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3270002)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3269933)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3269776)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3270003)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=3269934)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3269930)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3269931)[0m Fitting Client 7
Performing server side distillation training...
[2m[36m(launch_and_fit pid=3269930)[0m malloc_consolidate(): invalid chunk size
E0714 01:37:00.277479266 3443246 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 240000ms
Distillation training stopped at step number : 500
Average fusion training loss : 0.263323283970356, val accuracy : 0.5039017341040463, best val accuracy : 0.552690084481992
Average local training loss : 5.5365200730972
Average local training accuracy : 0.8238263888888888
INFO flwr 2023-07-14 01:37:56,773 | server.py:116 | fit progress: (3, 2.2973997456117594, {'server_test_acc': 0.4513927576601671}, 426.273282715003)
INFO flwr 2023-07-14 01:37:56,773 | server.py:163 | evaluate_round 3: no clients selected, cancel
DEBUG flwr 2023-07-14 01:38:04,823 | server.py:215 | fit_round 4: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3535633)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-07-14 01:39:23,896 | server.py:229 | fit_round 4 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3535641)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3535637)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3535638)[0m malloc_consolidate(): invalid chunk size
Cluster score for round 4 = 98258.640625
[2m[36m(launch_and_fit pid=3535639)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3535637)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3535641)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3535510)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3535633)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3535634)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3535638)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=3535636)[0m Fitting Client 2
Performing server side distillation training...
[2m[36m(launch_and_fit pid=3535510)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3535639)[0m corrupted size vs. prev_size in fastbins
E0714 01:39:25.270593864 3443500 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 480000ms
[2m[36m(launch_and_fit pid=3535636)[0m malloc_consolidate(): invalid chunk size
Distillation training stopped at step number : 500
Average fusion training loss : 0.2393883201479912, val accuracy : 0.5035904846598488, best val accuracy : 0.5302356602934638
Average local training loss : 5.584467407595366
Average local training accuracy : 0.824355709876543
INFO flwr 2023-07-14 01:40:23,855 | server.py:116 | fit progress: (4, 3.351345545999851, {'server_test_acc': 0.3380222841225627}, 573.3553205239587)
INFO flwr 2023-07-14 01:40:23,855 | server.py:163 | evaluate_round 4: no clients selected, cancel
DEBUG flwr 2023-07-14 01:40:31,985 | server.py:215 | fit_round 5: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-07-14 01:41:49,078 | server.py:229 | fit_round 5 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3798934)[0m double free or corruption (fasttop)
Cluster score for round 5 = 137178.6875
[2m[36m(launch_and_fit pid=3798934)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3799024)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3799025)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=3798935)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3799023)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3798936)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3798866)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3798795)[0m Fitting Client 10
Warm start at round 5
Performing server side distillation training...
[2m[36m(launch_and_fit pid=3799025)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=3798866)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3799024)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3798936)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3798795)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3798935)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3799023)[0m malloc_consolidate(): invalid chunk size
E0714 01:41:52.136195689 3685129 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 960000ms
Distillation training stopped at step number : 500
Average fusion training loss : 0.25265868377685546, val accuracy : 0.5284459759893285, best val accuracy : 0.5970431302801245
Average local training loss : 5.606299514137208
Average local training accuracy : 0.8222461419753087
INFO flwr 2023-07-14 01:42:52,414 | server.py:116 | fit progress: (5, 1.9484228346673227, {'server_test_acc': 0.5207520891364903}, 721.9144824049436)
INFO flwr 2023-07-14 01:42:52,414 | server.py:163 | evaluate_round 5: no clients selected, cancel
DEBUG flwr 2023-07-14 01:43:00,554 | server.py:215 | fit_round 6: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=4062467)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4062608)[0m double free or corruption (fasttop)
DEBUG flwr 2023-07-14 01:44:17,854 | server.py:229 | fit_round 6 received 8 results and 0 failures
Cluster score for round 6 = 76487.3046875
[2m[36m(launch_and_fit pid=4062608)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=4062609)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=4062539)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=4062638)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=4062607)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=4062678)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=4062469)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=4062467)[0m Fitting Client 7
Performing server side distillation training...
[2m[36m(launch_and_fit pid=4062607)[0m double free or corruption (fasttop)
E0714 01:44:18.493336781 3929897 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1920000ms
[2m[36m(launch_and_fit pid=4062469)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4062638)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4062539)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=4062609)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=4062678)[0m malloc_consolidate(): invalid chunk size
Distillation training stopped at step number : 500
Average fusion training loss : 0.17019970232248308, val accuracy : 0.5296353935082259, best val accuracy : 0.5762561138283682
Average local training loss : 4.664307919237763
Average local training accuracy : 0.8758796296296296
INFO flwr 2023-07-14 01:45:18,946 | server.py:116 | fit progress: (6, 1.9606441882991525, {'server_test_acc': 0.5350974930362117}, 868.4463511779904)
INFO flwr 2023-07-14 01:45:18,946 | server.py:163 | evaluate_round 6: no clients selected, cancel
DEBUG flwr 2023-07-14 01:45:53,697 | server.py:215 | fit_round 7: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=118294)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=118303)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=118296)[0m double free or corruption (fasttop)
DEBUG flwr 2023-07-14 01:47:12,767 | server.py:229 | fit_round 7 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=118298)[0m malloc_consolidate(): invalid chunk size
Cluster score for round 7 = 78675.25
[2m[36m(launch_and_fit pid=118292)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=118298)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=118295)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=118293)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=118294)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=118303)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=118291)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=118296)[0m Fitting Client 12
Performing server side distillation training...
[2m[36m(launch_and_fit pid=118293)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=118291)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=118295)[0m malloc_consolidate(): invalid chunk size
E0714 01:47:14.228261405  262858 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 3840000ms
[2m[36m(launch_and_fit pid=118292)[0m double free or corruption (fasttop)
Distillation training stopped at step number : 500
Average fusion training loss : 0.24068911457061767, val accuracy : 0.5923521565140063, best val accuracy : 0.6341707425522455
Average local training loss : 4.75633544512093
Average local training accuracy : 0.8710347222222222
INFO flwr 2023-07-14 01:48:14,939 | server.py:116 | fit progress: (7, 2.068109195146056, {'server_test_acc': 0.5416434540389972}, 1044.4391573809553)
INFO flwr 2023-07-14 01:48:14,939 | server.py:163 | evaluate_round 7: no clients selected, cancel
DEBUG flwr 2023-07-14 01:48:23,061 | server.py:215 | fit_round 8: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=335804)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=335989)[0m double free or corruption (fasttop)
DEBUG flwr 2023-07-14 01:49:38,774 | server.py:229 | fit_round 8 received 8 results and 0 failures
Cluster score for round 8 = 67391.59375
[2m[36m(launch_and_fit pid=335804)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=335973)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=335790)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=335989)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=335971)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=335794)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=335786)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=335972)[0m Fitting Client 2
Performing server side distillation training...
[2m[36m(launch_and_fit pid=335790)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=335973)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=335794)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=335971)[0m double free or corruption (fasttop)
E0714 01:49:40.314241211  263532 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 7680000ms
[2m[36m(launch_and_fit pid=335972)[0m corrupted size vs. prev_size in fastbins
Distillation training stopped at step number : 500
Average fusion training loss : 0.2171589134335518, val accuracy : 0.427134281903068, best val accuracy : 0.45164517563361495
Average local training loss : 4.739053583424539
Average local training accuracy : 0.8731597222222222
INFO flwr 2023-07-14 01:50:38,040 | server.py:116 | fit progress: (8, 1.913262253020135, {'server_test_acc': 0.48008356545961}, 1187.5405844749184)
INFO flwr 2023-07-14 01:50:38,040 | server.py:163 | evaluate_round 8: no clients selected, cancel
DEBUG flwr 2023-07-14 01:50:46,384 | server.py:215 | fit_round 9: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=604219)[0m double free or corruption (fasttop)
DEBUG flwr 2023-07-14 01:52:06,581 | server.py:229 | fit_round 9 received 8 results and 0 failures
Cluster score for round 9 = 77884.328125
[2m[36m(launch_and_fit pid=604213)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=604217)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=604214)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=604216)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=604218)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=604219)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=604221)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=604220)[0m Fitting Client 12
Performing server side distillation training...
[2m[36m(launch_and_fit pid=604214)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=604216)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=604220)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=604217)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=604221)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=604218)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=604213)[0m corrupted size vs. prev_size in fastbins
E0714 01:52:08.956555442  521644 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 15360000ms
E0714 01:52:38.760726027  786834 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 30720000ms
Distillation training stopped at step number : 500
Average fusion training loss : 0.26163138043880463, val accuracy : 0.4545020008892841, best val accuracy : 0.5261227212094264
Average local training loss : 4.813442694116384
Average local training accuracy : 0.8678202160493826
INFO flwr 2023-07-14 01:53:05,612 | server.py:116 | fit progress: (9, 1.91239190832154, {'server_test_acc': 0.4981894150417827}, 1335.1128793730168)
INFO flwr 2023-07-14 01:53:05,613 | server.py:163 | evaluate_round 9: no clients selected, cancel
DEBUG flwr 2023-07-14 01:53:13,866 | server.py:215 | fit_round 10: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=871265)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=871264)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-07-14 01:54:31,531 | server.py:229 | fit_round 10 received 8 results and 0 failures
Cluster score for round 10 = 75263.1328125
[2m[36m(launch_and_fit pid=871265)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=871404)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=871336)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=871264)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=871263)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=871335)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=871405)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=871334)[0m Fitting Client 13
Warm start at round 10
Performing server side distillation training...
[2m[36m(launch_and_fit pid=871263)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=871335)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=871334)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=871336)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=871405)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=871404)[0m double free or corruption (fasttop)
Distillation training stopped at step number : 500
Average fusion training loss : 0.2871992264986038, val accuracy : 0.56776345042241, best val accuracy : 0.6158292574477545
Average local training loss : 4.845056846085936
Average local training accuracy : 0.8658001543209877
INFO flwr 2023-07-14 01:55:37,437 | server.py:116 | fit progress: (10, 2.2075465810664183, {'server_test_acc': 0.5083565459610028}, 1486.9376797529403)
INFO flwr 2023-07-14 01:55:37,437 | server.py:163 | evaluate_round 10: no clients selected, cancel
DEBUG flwr 2023-07-14 01:55:45,490 | server.py:215 | fit_round 11: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1138053)[0m double free or corruption (fasttop)
DEBUG flwr 2023-07-14 01:57:02,889 | server.py:229 | fit_round 11 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1138090)[0m malloc_consolidate(): invalid chunk size
Cluster score for round 11 = 40182.1328125
[2m[36m(launch_and_fit pid=1138089)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1138017)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1138088)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1138021)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1138016)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1138090)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1138053)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1138087)[0m Fitting Client 5
Performing server side distillation training...
[2m[36m(launch_and_fit pid=1138088)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1138087)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1138017)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1138016)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1138021)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1138089)[0m double free or corruption (fasttop)
E0714 01:57:07.748698048  828259 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 61440000ms
E0714 01:57:59.772960427 1385611 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 122880000ms
Distillation training stopped at step number : 500
Average fusion training loss : 0.2658000711798668, val accuracy : 0.5342374388617163, best val accuracy : 0.5869275233437083
Average local training loss : 3.9911108887754376
Average local training accuracy : 0.9132646604938272
INFO flwr 2023-07-14 01:58:04,339 | server.py:116 | fit progress: (11, 1.6257127103035165, {'server_test_acc': 0.6185236768802228}, 1633.839454419911)
INFO flwr 2023-07-14 01:58:04,339 | server.py:163 | evaluate_round 11: no clients selected, cancel
DEBUG flwr 2023-07-14 01:58:12,563 | server.py:215 | fit_round 12: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1398667)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1398597)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1398668)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1398598)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1398666)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1398595)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-07-14 01:59:58,266 | server.py:229 | fit_round 12 received 8 results and 0 failures
Cluster score for round 12 = 55543.859375
[2m[36m(launch_and_fit pid=1398667)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1398597)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=1398598)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1398596)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1398666)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1398668)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1398526)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=1398595)[0m Fitting Client 16
Performing server side distillation training...
[2m[36m(launch_and_fit pid=1398526)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1398596)[0m malloc_consolidate(): invalid chunk size
E0714 02:00:06.883913038 1533013 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 245760000ms
Distillation training stopped at step number : 500
Average fusion training loss : 0.2379824532866478, val accuracy : 0.5929746554024011, best val accuracy : 0.6257225433526011
Average local training loss : 3.984174367878586
Average local training accuracy : 0.9133703703703704
INFO flwr 2023-07-14 02:01:00,370 | server.py:116 | fit progress: (12, 1.501328348781405, {'server_test_acc': 0.5721448467966573}, 1809.8708309339127)
INFO flwr 2023-07-14 02:01:00,371 | server.py:163 | evaluate_round 12: no clients selected, cancel
DEBUG flwr 2023-07-14 02:01:08,844 | server.py:215 | fit_round 13: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1657918)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1658225)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1658072)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1658073)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-07-14 02:02:27,298 | server.py:229 | fit_round 13 received 8 results and 0 failures
Cluster score for round 13 = 67105.4140625
[2m[36m(launch_and_fit pid=1657918)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1657922)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1658224)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1658225)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1658072)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1658171)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1658073)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1658244)[0m Fitting Client 5
Performing server side distillation training...
[2m[36m(launch_and_fit pid=1658224)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1658244)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1657922)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1658171)[0m malloc_consolidate(): invalid chunk size
E0714 02:02:29.401176232 1800229 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 491520000ms
Distillation training stopped at step number : 500
Average fusion training loss : 0.2211505838930607, val accuracy : 0.5512894619831036, best val accuracy : 0.5698088039128502
Average local training loss : 4.101325348298997
Average local training accuracy : 0.9065640432098766
INFO flwr 2023-07-14 02:03:28,424 | server.py:116 | fit progress: (13, 2.195318742449237, {'server_test_acc': 0.49972144846796657}, 1957.9244175190106)
INFO flwr 2023-07-14 02:03:28,424 | server.py:163 | evaluate_round 13: no clients selected, cancel
DEBUG flwr 2023-07-14 02:03:36,628 | server.py:215 | fit_round 14: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-07-14 02:04:53,942 | server.py:229 | fit_round 14 received 8 results and 0 failures
Cluster score for round 14 = 66592.078125
[2m[36m(launch_and_fit pid=1902962)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1902696)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1903160)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=1902578)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1903157)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1902963)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=1903141)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1903159)[0m Fitting Client 16
Performing server side distillation training...
[2m[36m(launch_and_fit pid=1903159)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1902962)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1903157)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1902696)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1902578)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1902963)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=1903160)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1903141)[0m malloc_consolidate(): invalid chunk size
E0714 02:04:56.947049527 2063431 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 983040000ms
Distillation training stopped at step number : 500
Average fusion training loss : 0.23692056161165237, val accuracy : 0.6601044908848377, best val accuracy : 0.6786349488661627
Average local training loss : 4.161936848331243
Average local training accuracy : 0.904954475308642
INFO flwr 2023-07-14 02:05:53,465 | server.py:116 | fit progress: (14, 1.7998286786517725, {'server_test_acc': 0.579108635097493}, 2102.9654635039624)
INFO flwr 2023-07-14 02:05:53,465 | server.py:163 | evaluate_round 14: no clients selected, cancel
DEBUG flwr 2023-07-14 02:06:01,647 | server.py:215 | fit_round 15: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-07-14 02:07:17,163 | server.py:229 | fit_round 15 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=2141935)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2141941)[0m double free or corruption (fasttop)
Cluster score for round 15 = 61164.44921875
[2m[36m(launch_and_fit pid=2141667)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=2141942)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2141939)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2141935)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=2141665)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2141671)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=2141936)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2141941)[0m Fitting Client 8
Warm start at round 15
Performing server side distillation training...
[2m[36m(launch_and_fit pid=2141942)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2141665)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2141671)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2141667)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2141936)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2141939)[0m malloc_consolidate(): invalid chunk size
E0714 02:07:19.776512713 2064516 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): 1966080000ms
E0714 02:08:11.339453408 2394407 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
Distillation training stopped at step number : 500
Average fusion training loss : 0.3619451824426651, val accuracy : 0.4756447309915518, best val accuracy : 0.5108937305469098
Average local training loss : 4.247103790380061
Average local training accuracy : 0.9001697530864198
INFO flwr 2023-07-14 02:08:17,425 | server.py:116 | fit progress: (15, 2.459502634032523, {'server_test_acc': 0.5227019498607243}, 2246.925546820974)
INFO flwr 2023-07-14 02:08:17,425 | server.py:163 | evaluate_round 15: no clients selected, cancel
DEBUG flwr 2023-07-14 02:08:25,550 | server.py:215 | fit_round 16: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2405703)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2405704)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2405707)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2405706)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2405708)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=2405705)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2405702)[0m double free or corruption (fasttop)
DEBUG flwr 2023-07-14 02:09:46,624 | server.py:229 | fit_round 16 received 8 results and 0 failures
Cluster score for round 16 = 30440.65625
[2m[36m(launch_and_fit pid=2405707)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2405705)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=2405704)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=2405708)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2405702)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2405709)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=2405703)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=2405706)[0m Fitting Client 10
Performing server side distillation training...
E0714 02:09:48.074298912 2586203 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0714 02:09:48.074381550 2586203 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2405709)[0m double free or corruption (fasttop)
Distillation training stopped at step number : 500
Average fusion training loss : 0.24458277016878127, val accuracy : 0.4876056024899956, best val accuracy : 0.5165629168519342
Average local training loss : 3.5274839397519826
Average local training accuracy : 0.9374807098765432
INFO flwr 2023-07-14 02:10:47,064 | server.py:116 | fit progress: (16, 1.9554897659004233, {'server_test_acc': 0.5501392757660167}, 2396.564993103966)
INFO flwr 2023-07-14 02:10:47,065 | server.py:163 | evaluate_round 16: no clients selected, cancel
DEBUG flwr 2023-07-14 02:10:55,460 | server.py:215 | fit_round 17: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2674215)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=2674236)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2674486)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2674244)[0m double free or corruption (fasttop)
DEBUG flwr 2023-07-14 02:12:12,955 | server.py:229 | fit_round 17 received 8 results and 0 failures
Cluster score for round 17 = 27454.056640625
[2m[36m(launch_and_fit pid=2674483)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2674215)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2674485)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=2674236)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2674414)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=2674486)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2674237)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=2674244)[0m Fitting Client 15
Performing server side distillation training...
[2m[36m(launch_and_fit pid=2674237)[0m malloc_consolidate(): invalid chunk size
E0714 02:12:13.945429734 2588166 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=2674485)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2674414)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2674483)[0m malloc_consolidate(): invalid chunk size
Distillation training stopped at step number : 500
Average fusion training loss : 0.2589211145937443, val accuracy : 0.6147510004446419, best val accuracy : 0.6649622054246331
Average local training loss : 3.6291988984681667
Average local training accuracy : 0.932554012345679
INFO flwr 2023-07-14 02:13:14,265 | server.py:116 | fit progress: (17, 1.1969418613359457, {'server_test_acc': 0.6949860724233984}, 2543.7660215810174)
INFO flwr 2023-07-14 02:13:14,266 | server.py:163 | evaluate_round 17: no clients selected, cancel
DEBUG flwr 2023-07-14 02:13:22,409 | server.py:215 | fit_round 18: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=2939968)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2939896)[0m double free or corruption (fasttop)
DEBUG flwr 2023-07-14 02:14:39,586 | server.py:229 | fit_round 18 received 8 results and 0 failures
Cluster score for round 18 = 39636.40625
[2m[36m(launch_and_fit pid=2939967)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=2939827)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=2939896)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=2939969)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=2939899)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=2939970)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=2939898)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=2939968)[0m Fitting Client 18
Performing server side distillation training...
[2m[36m(launch_and_fit pid=2939967)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2939898)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2939970)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=2939899)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2939969)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=2939827)[0m double free or corruption (fasttop)
E0714 02:14:44.065359538 3083584 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
Distillation training stopped at step number : 500
Average fusion training loss : 0.24270012417435646, val accuracy : 0.6503890618052468, best val accuracy : 0.6702979101823032
Average local training loss : 3.6623816831037406
Average local training accuracy : 0.931125
INFO flwr 2023-07-14 02:15:41,798 | server.py:116 | fit progress: (18, 0.9777171360749056, {'server_test_acc': 0.7593314763231198}, 2691.2984758589882)
INFO flwr 2023-07-14 02:15:41,798 | server.py:163 | evaluate_round 18: no clients selected, cancel
DEBUG flwr 2023-07-14 02:15:49,895 | server.py:215 | fit_round 19: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3204364)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-07-14 02:17:07,067 | server.py:229 | fit_round 19 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3204505)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3204361)[0m double free or corruption (fasttop)
Cluster score for round 19 = 43510.73828125
[2m[36m(launch_and_fit pid=3204505)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3204361)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3204434)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=3204366)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3204436)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=3204435)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=3204504)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3204364)[0m Fitting Client 7
Performing server side distillation training...
[2m[36m(launch_and_fit pid=3204504)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3204436)[0m malloc_consolidate(): invalid chunk size
E0714 02:17:08.601083973 3330849 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=3204434)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3204366)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3204435)[0m malloc_consolidate(): invalid chunk size
Distillation training stopped at step number : 500
Average fusion training loss : 0.28340513721108435, val accuracy : 0.6014117385504669, best val accuracy : 0.6229435304579813
Average local training loss : 3.6007695774547757
Average local training accuracy : 0.9342862654320988
INFO flwr 2023-07-14 02:18:10,193 | server.py:116 | fit progress: (19, 1.5697920196235677, {'server_test_acc': 0.581058495821727}, 2839.6931308049243)
INFO flwr 2023-07-14 02:18:10,193 | server.py:163 | evaluate_round 19: no clients selected, cancel
DEBUG flwr 2023-07-14 02:18:18,448 | server.py:215 | fit_round 20: strategy sampled 8 clients (out of 20)
DEBUG flwr 2023-07-14 02:19:35,969 | server.py:229 | fit_round 20 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3466674)[0m double free or corruption (fasttop)
Cluster score for round 20 = 35737.11328125
[2m[36m(launch_and_fit pid=3466679)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3466677)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3466678)[0m Fitting Client 4
[2m[36m(launch_and_fit pid=3466681)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3466675)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=3466682)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=3466674)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3466680)[0m Fitting Client 3
Warm start at round 20
Performing server side distillation training...
[2m[36m(launch_and_fit pid=3466677)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3466682)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3466678)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3466679)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3466681)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3466680)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3466675)[0m double free or corruption (fasttop)
E0714 02:19:39.014891889 3331257 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
Distillation training stopped at step number : 500
Average fusion training loss : 0.3138969353735447, val accuracy : 0.584370831480658, best val accuracy : 0.6726322810137839
Average local training loss : 3.7323649737052618
Average local training accuracy : 0.928048611111111
INFO flwr 2023-07-14 02:20:36,506 | server.py:116 | fit progress: (20, 1.5431064069105058, {'server_test_acc': 0.6194986072423398}, 2986.0061805619625)
INFO flwr 2023-07-14 02:20:36,506 | server.py:163 | evaluate_round 20: no clients selected, cancel
DEBUG flwr 2023-07-14 02:20:45,091 | server.py:215 | fit_round 21: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3708804)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-07-14 02:22:02,873 | server.py:229 | fit_round 21 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=3708801)[0m double free or corruption (fasttop)
Cluster score for round 21 = 18329.05859375
[2m[36m(launch_and_fit pid=3708804)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=3708924)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=3708948)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3708943)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=3708947)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3708946)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3708801)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=3708925)[0m Fitting Client 17
Performing server side distillation training...
[2m[36m(launch_and_fit pid=3708948)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3708943)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3708946)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3708947)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3708925)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3708924)[0m double free or corruption (fasttop)
Distillation training stopped at step number : 500
Average fusion training loss : 0.2450222741663456, val accuracy : 0.6167296576256114, best val accuracy : 0.6430635838150289
Average local training loss : 3.2629424165934324
Average local training accuracy : 0.9516319444444444
INFO flwr 2023-07-14 02:23:02,441 | server.py:116 | fit progress: (21, 2.7186206549323035, {'server_test_acc': 0.5231197771587743}, 3131.9411438630195)
INFO flwr 2023-07-14 02:23:02,441 | server.py:163 | evaluate_round 21: no clients selected, cancel
DEBUG flwr 2023-07-14 02:23:10,751 | server.py:215 | fit_round 22: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=3950865)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-07-14 02:24:27,375 | server.py:229 | fit_round 22 received 8 results and 0 failures
Cluster score for round 22 = 42281.953125
[2m[36m(launch_and_fit pid=3950864)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=3950979)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=3950865)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=3950943)[0m Fitting Client 11
[2m[36m(launch_and_fit pid=3950710)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=3950881)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=3950981)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=3950866)[0m Fitting Client 3
Performing server side distillation training...
[2m[36m(launch_and_fit pid=3950866)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3950979)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3950881)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3950710)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3950981)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=3950864)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=3950943)[0m double free or corruption (fasttop)
E0714 02:24:42.740580438 4140612 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0714 02:25:13.594524278 4147137 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
Distillation training stopped at step number : 500
Average fusion training loss : 0.21414628985524178, val accuracy : 0.638494886616274, best val accuracy : 0.6631836371720765
Average local training loss : 3.290198756661266
Average local training accuracy : 0.9502461419753087
INFO flwr 2023-07-14 02:25:27,301 | server.py:116 | fit progress: (22, 1.4479392025132034, {'server_test_acc': 0.5987465181058496}, 3276.801149089937)
INFO flwr 2023-07-14 02:25:27,301 | server.py:163 | evaluate_round 22: no clients selected, cancel
DEBUG flwr 2023-07-14 02:25:35,547 | server.py:215 | fit_round 23: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=13377)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-07-14 02:26:50,857 | server.py:229 | fit_round 23 received 8 results and 0 failures
Cluster score for round 23 = 37385.13671875
[2m[36m(launch_and_fit pid=13377)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=13379)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=13380)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=13381)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=13400)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=13378)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=13399)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=13398)[0m Fitting Client 16
Performing server side distillation training...
[2m[36m(launch_and_fit pid=13380)[0m malloc_consolidate(): invalid chunk size
E0714 02:26:51.819615720 4189797 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=13399)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=13378)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=13400)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=13381)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=13398)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=13379)[0m malloc_consolidate(): invalid chunk size
Distillation training stopped at step number : 500
Average fusion training loss : 0.23592470315098762, val accuracy : 0.637894619831036, best val accuracy : 0.6671854157403291
Average local training loss : 3.40061942813918
Average local training accuracy : 0.9449074074074073
INFO flwr 2023-07-14 02:28:25,226 | server.py:116 | fit progress: (23, 2.2986015402174926, {'server_test_acc': 0.6389972144846797}, 3454.7263061649865)
INFO flwr 2023-07-14 02:28:25,226 | server.py:163 | evaluate_round 23: no clients selected, cancel
DEBUG flwr 2023-07-14 02:28:33,605 | server.py:215 | fit_round 24: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=283502)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=283352)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=283355)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=283434)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=283503)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-07-14 02:30:16,403 | server.py:229 | fit_round 24 received 8 results and 0 failures
Cluster score for round 24 = 38101.328125
[2m[36m(launch_and_fit pid=283353)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=283432)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=283352)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=283503)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=283434)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=283355)[0m Fitting Client 7
[2m[36m(launch_and_fit pid=283502)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=283504)[0m Fitting Client 13
Performing server side distillation training...
[2m[36m(launch_and_fit pid=283432)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=283504)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=283353)[0m malloc_consolidate(): invalid chunk size
E0714 02:30:18.730008233  195141 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0714 02:31:09.602077480  447538 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
Distillation training stopped at step number : 500
Average fusion training loss : 0.2467777000963688, val accuracy : 0.6937083148065807, best val accuracy : 0.7086482881280569
Average local training loss : 3.3103661498986185
Average local training accuracy : 0.949630401234568
INFO flwr 2023-07-14 02:31:17,737 | server.py:116 | fit progress: (24, 2.0090891864638474, {'server_test_acc': 0.6816155988857938}, 3627.2374461529544)
INFO flwr 2023-07-14 02:31:17,737 | server.py:163 | evaluate_round 24: no clients selected, cancel
DEBUG flwr 2023-07-14 02:31:26,012 | server.py:215 | fit_round 25: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=549491)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=549465)[0m double free or corruption (fasttop)
DEBUG flwr 2023-07-14 02:32:43,216 | server.py:229 | fit_round 25 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=549348)[0m double free or corruption (fasttop)
Cluster score for round 25 = 48662.25
[2m[36m(launch_and_fit pid=549422)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=549348)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=549420)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=549492)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=549465)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=549491)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=549419)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=549421)[0m Fitting Client 0
Warm start at round 25
Performing server side distillation training...
[2m[36m(launch_and_fit pid=549421)[0m corrupted size vs. prev_size in fastbins
[2m[36m(launch_and_fit pid=549419)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=549420)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=549422)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=549492)[0m malloc_consolidate(): invalid chunk size
E0714 02:32:45.482473031  691582 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
Distillation training stopped at step number : 500
Average fusion training loss : 0.2924447552263737, val accuracy : 0.6032570031124945, best val accuracy : 0.6550689195197865
Average local training loss : 3.418588612787425
Average local training accuracy : 0.9438333333333333
INFO flwr 2023-07-14 02:33:44,893 | server.py:116 | fit progress: (25, 2.9852526951633123, {'server_test_acc': 0.5785515320334261}, 3774.393126250012)
INFO flwr 2023-07-14 02:33:44,893 | server.py:163 | evaluate_round 25: no clients selected, cancel
DEBUG flwr 2023-07-14 02:33:53,073 | server.py:215 | fit_round 26: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=813602)[0m double free or corruption (fasttop)
DEBUG flwr 2023-07-14 02:35:09,942 | server.py:229 | fit_round 26 received 8 results and 0 failures
Cluster score for round 26 = 23562.21875
[2m[36m(launch_and_fit pid=813604)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=813601)[0m Fitting Client 6
[2m[36m(launch_and_fit pid=813602)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=813603)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=813599)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=813593)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=813600)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=813598)[0m Fitting Client 13
Performing server side distillation training...
[2m[36m(launch_and_fit pid=813604)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=813601)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=813599)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=813600)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=813600)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=813598)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=813603)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=813593)[0m malloc_consolidate(): invalid chunk size
E0714 02:35:12.392883157  938261 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
E0714 02:35:35.018410066  984080 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
Distillation training stopped at step number : 500
Average fusion training loss : 0.20712713053822518, val accuracy : 0.6839595375722543, best val accuracy : 0.726878612716763
Average local training loss : 3.174697178602218
Average local training accuracy : 0.9562623456790124
INFO flwr 2023-07-14 02:36:11,918 | server.py:116 | fit progress: (26, 2.50907895744345, {'server_test_acc': 0.6502785515320334}, 3921.4181799659273)
INFO flwr 2023-07-14 02:36:11,918 | server.py:163 | evaluate_round 26: no clients selected, cancel
DEBUG flwr 2023-07-14 02:36:20,152 | server.py:215 | fit_round 27: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1075615)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1075616)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1075621)[0m double free or corruption (fasttop)
DEBUG flwr 2023-07-14 02:37:37,074 | server.py:229 | fit_round 27 received 8 results and 0 failures
Cluster score for round 27 = 25097.72265625
[2m[36m(launch_and_fit pid=1075615)[0m Fitting Client 18
[2m[36m(launch_and_fit pid=1075616)[0m Fitting Client 12
[2m[36m(launch_and_fit pid=1075475)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1075618)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1075617)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1075621)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1075547)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1075660)[0m Fitting Client 16
Performing server side distillation training...
[2m[36m(launch_and_fit pid=1075547)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1075475)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1075617)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1075660)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1075618)[0m double free or corruption (fasttop)
E0714 02:37:41.356587942 1213880 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
Distillation training stopped at step number : 500
Average fusion training loss : 0.21731660759449006, val accuracy : 0.739217429968875, best val accuracy : 0.7806803023566029
Average local training loss : 3.1063968295231463
Average local training accuracy : 0.9599212962962963
INFO flwr 2023-07-14 02:38:37,732 | server.py:116 | fit progress: (27, 2.0706647005585905, {'server_test_acc': 0.7236768802228413}, 4067.232365846983)
INFO flwr 2023-07-14 02:38:37,732 | server.py:163 | evaluate_round 27: no clients selected, cancel
DEBUG flwr 2023-07-14 02:38:45,959 | server.py:215 | fit_round 28: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1315860)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1315721)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-07-14 02:40:04,013 | server.py:229 | fit_round 28 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1315857)[0m double free or corruption (fasttop)
Cluster score for round 28 = 41931.1953125
[2m[36m(launch_and_fit pid=1315712)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1315857)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1315722)[0m Fitting Client 13
[2m[36m(launch_and_fit pid=1315720)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1315881)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1315721)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1315860)[0m Fitting Client 3
[2m[36m(launch_and_fit pid=1315856)[0m Fitting Client 4
Performing server side distillation training...
[2m[36m(launch_and_fit pid=1315722)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1315712)[0m malloc_consolidate(): invalid chunk size
E0714 02:40:04.645420301 1473239 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1315720)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1315881)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1315856)[0m malloc_consolidate(): invalid chunk size
Distillation training stopped at step number : 500
Average fusion training loss : 0.20342188042402268, val accuracy : 0.7512005335704758, best val accuracy : 0.7781236104935527
Average local training loss : 3.144372268114239
Average local training accuracy : 0.9581257716049384
INFO flwr 2023-07-14 02:41:04,355 | server.py:116 | fit progress: (28, 4.776995157199318, {'server_test_acc': 0.7525069637883008}, 4213.8551555320155)
INFO flwr 2023-07-14 02:41:04,355 | server.py:163 | evaluate_round 28: no clients selected, cancel
DEBUG flwr 2023-07-14 02:41:12,608 | server.py:215 | fit_round 29: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1558890)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1558888)[0m malloc_consolidate(): invalid chunk size
DEBUG flwr 2023-07-14 02:42:29,177 | server.py:229 | fit_round 29 received 8 results and 0 failures
[2m[36m(launch_and_fit pid=1558749)[0m double free or corruption (fasttop)
Cluster score for round 29 = 56167.67578125
[2m[36m(launch_and_fit pid=1558887)[0m Fitting Client 10
[2m[36m(launch_and_fit pid=1558749)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1558889)[0m Fitting Client 0
[2m[36m(launch_and_fit pid=1558783)[0m Fitting Client 17
[2m[36m(launch_and_fit pid=1558886)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1558891)[0m Fitting Client 9
[2m[36m(launch_and_fit pid=1558890)[0m Fitting Client 14
[2m[36m(launch_and_fit pid=1558888)[0m Fitting Client 18
Performing server side distillation training...
[2m[36m(launch_and_fit pid=1558886)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1558889)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1558783)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1558891)[0m malloc_consolidate(): invalid chunk size
E0714 02:42:30.738833771 1736505 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1558887)[0m double free or corruption (fasttop)
Distillation training stopped at step number : 500
Average fusion training loss : 0.22382084637880326, val accuracy : 0.7163739439751, best val accuracy : 0.7544464206313918
Average local training loss : 3.1132152023725213
Average local training accuracy : 0.95925
INFO flwr 2023-07-14 02:43:34,637 | server.py:116 | fit progress: (29, 3.4567497508439513, {'server_test_acc': 0.6162952646239555}, 4364.137958084932)
INFO flwr 2023-07-14 02:43:34,638 | server.py:163 | evaluate_round 29: no clients selected, cancel
DEBUG flwr 2023-07-14 02:44:00,932 | server.py:215 | fit_round 30: strategy sampled 8 clients (out of 20)
[2m[36m(launch_and_fit pid=1816107)[0m double free or corruption (fasttop)
DEBUG flwr 2023-07-14 02:45:16,906 | server.py:229 | fit_round 30 received 8 results and 0 failures
Cluster score for round 30 = 53014.6015625
[2m[36m(launch_and_fit pid=1816106)[0m Fitting Client 1
[2m[36m(launch_and_fit pid=1816105)[0m Fitting Client 8
[2m[36m(launch_and_fit pid=1816104)[0m Fitting Client 5
[2m[36m(launch_and_fit pid=1816100)[0m Fitting Client 16
[2m[36m(launch_and_fit pid=1816108)[0m Fitting Client 19
[2m[36m(launch_and_fit pid=1816107)[0m Fitting Client 2
[2m[36m(launch_and_fit pid=1816102)[0m Fitting Client 15
[2m[36m(launch_and_fit pid=1816103)[0m Fitting Client 18
Warm start at round 30
Performing server side distillation training...
[2m[36m(launch_and_fit pid=1816105)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1816104)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1816100)[0m double free or corruption (fasttop)
[2m[36m(launch_and_fit pid=1816103)[0m malloc_consolidate(): invalid chunk size
E0714 02:45:18.441240780 1736844 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
[2m[36m(launch_and_fit pid=1816106)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1816108)[0m malloc_consolidate(): invalid chunk size
[2m[36m(launch_and_fit pid=1816102)[0m malloc_consolidate(): invalid chunk size
E0714 02:45:36.582514944 2023264 chttp2_transport.cc:1079]             ipv4:145.136.62.36:53231: Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings". Current keepalive time (before throttling): ∞
Distillation training stopped at step number : 500
Average fusion training loss : 0.2966269382238388, val accuracy : 0.6217318808359271, best val accuracy : 0.6961983103601601
Average local training loss : 3.1819992892444136
Average local training accuracy : 0.9558603395061728
INFO flwr 2023-07-14 02:46:18,057 | server.py:116 | fit progress: (30, 3.07936346484426, {'server_test_acc': 0.7137883008356546}, 4527.557123793988)
INFO flwr 2023-07-14 02:46:18,057 | server.py:163 | evaluate_round 30: no clients selected, cancel
INFO flwr 2023-07-14 02:46:18,057 | server.py:144 | FL finished in 4527.557463987963
INFO flwr 2023-07-14 02:46:18,057 | app.py:202 | app_fit: losses_distributed []
INFO flwr 2023-07-14 02:46:18,058 | app.py:203 | app_fit: metrics_distributed {}
INFO flwr 2023-07-14 02:46:18,058 | app.py:204 | app_fit: losses_centralized [(0, 2.1845225108367154), (1, 3.2893234667339697), (2, 2.426374108147156), (3, 2.2973997456117594), (4, 3.351345545999851), (5, 1.9484228346673227), (6, 1.9606441882991525), (7, 2.068109195146056), (8, 1.913262253020135), (9, 1.91239190832154), (10, 2.2075465810664183), (11, 1.6257127103035165), (12, 1.501328348781405), (13, 2.195318742449237), (14, 1.7998286786517725), (15, 2.459502634032523), (16, 1.9554897659004233), (17, 1.1969418613359457), (18, 0.9777171360749056), (19, 1.5697920196235677), (20, 1.5431064069105058), (21, 2.7186206549323035), (22, 1.4479392025132034), (23, 2.2986015402174926), (24, 2.0090891864638474), (25, 2.9852526951633123), (26, 2.50907895744345), (27, 2.0706647005585905), (28, 4.776995157199318), (29, 3.4567497508439513), (30, 3.07936346484426)]
INFO flwr 2023-07-14 02:46:18,058 | app.py:205 | app_fit: metrics_centralized {'server_test_acc': [(0, 0.11030640668523677), (1, 0.4488857938718663), (2, 0.42938718662952646), (3, 0.4513927576601671), (4, 0.3380222841225627), (5, 0.5207520891364903), (6, 0.5350974930362117), (7, 0.5416434540389972), (8, 0.48008356545961), (9, 0.4981894150417827), (10, 0.5083565459610028), (11, 0.6185236768802228), (12, 0.5721448467966573), (13, 0.49972144846796657), (14, 0.579108635097493), (15, 0.5227019498607243), (16, 0.5501392757660167), (17, 0.6949860724233984), (18, 0.7593314763231198), (19, 0.581058495821727), (20, 0.6194986072423398), (21, 0.5231197771587743), (22, 0.5987465181058496), (23, 0.6389972144846797), (24, 0.6816155988857938), (25, 0.5785515320334261), (26, 0.6502785515320334), (27, 0.7236768802228413), (28, 0.7525069637883008), (29, 0.6162952646239555), (30, 0.7137883008356546)]}
malloc_consolidate(): invalid chunk size
srun: error: gcn36: task 0: Aborted
srun: launch/slurm: _step_signal: Terminating StepId=3063431.1
-----EXPERIMENT ENDS-----
-----END-----

JOB STATISTICS
==============
Job ID: 3063431
Cluster: snellius
User/Group: sunnys/sunnys
State: RUNNING
Nodes: 1
Cores per node: 18
CPU Utilized: 02:42:01
CPU Efficiency: 11.67% of 23:08:42 core-walltime
Job Wall-clock time: 01:17:09
Memory Utilized: 64.83 GB
Memory Efficiency: 54.02% of 120.00 GB
WARNING: Efficiency statistics may be misleading for RUNNING jobs.
